import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from 'react-router-dom'
import './styles.css'
import './design-overrides.css'

type Product = { product_id: string; name: string; garment_type: string; description: string; colors: string; search_tags: string; image_file_path: string; price: number }
type Stock = { size: string; quantity: number }
type ChatMatch = { product_id: string; name: string; garment_type: string; description: string; price: number; image_file_path: string }
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000'
const imageUrl = (p: Product) => `${API}/images/${p.image_file_path.split('/').pop()}`

function Layout({ children }: { children: React.ReactNode }) {
  const location = useLocation()
  const [chatOpen, setChatOpen] = useState(false)
  const [messages, setMessages] = useState<string[]>(['Hi! I’m the Campus Concierge. Ask me about products, prices, or available sizes.'])
  const [matches, setMatches] = useState<ChatMatch[]>([])
  const [draft, setDraft] = useState('')
  const [userId, setUserId] = useState<number | null>(() => Number(localStorage.getItem('campus_customs_user_id')) || null)
  useEffect(() => { const syncUser = () => setUserId(Number(localStorage.getItem('campus_customs_user_id')) || null); window.addEventListener('campus-customs-auth', syncUser); return () => window.removeEventListener('campus-customs-auth', syncUser) }, [])
  useEffect(() => { if (userId) fetch(`${API}/api/chat/history/${userId}`).then(r => { if (!r.ok) throw new Error('History unavailable'); return r.json() }).then(data => { if (data.messages?.length) setMessages(data.messages.map((item: { role: string; content: string }) => item.role === 'user' ? `You: ${item.content}` : item.content)) }).catch(() => {}) }, [userId])
  const send = async (event: React.FormEvent) => { event.preventDefault(); const message = draft.trim(); if (!message) return; setMessages(old => [...old, `You: ${message}`]); setDraft(''); try { const productId = location.pathname.startsWith('/products/') ? location.pathname.split('/')[2] : undefined; const response = await fetch(`${API}/api/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message, user_id: userId, current_page: location.pathname, product_id: productId }) }); const data = await response.json(); if (response.ok) { setMessages(old => [...old, data.answer]); setMatches(data.matches || []) } else { setMessages(old => [...old, 'Sorry, chat is temporarily unavailable.']); setMatches([]) } } catch { setMessages(old => [...old, 'Sorry, chat is temporarily unavailable.']); setMatches([]) } }
  return <><header><Link className="brand" to="/"><span className="mark">CC</span> CAMPUS <b>CUSTOMS</b></Link><nav><Link to="/">Home</Link><Link to="/products">Products</Link><Link to="/about">About Us</Link><Link to="/login">Log in</Link><Link className="account" to="/create-account">Create account</Link></nav></header><main>{children}</main><footer><b>Campus Customs</b><span>Made for the memories you make here.</span><span>© 2026 Campus Customs</span></footer><button className="chat-fab" onClick={() => setChatOpen(!chatOpen)} aria-label="Open chat">✦</button>{chatOpen && <div className="chat-box"><div className="chat-head">Campus Concierge <button onClick={() => setChatOpen(false)}>×</button></div><div className="chat-body">{messages.map((message, index) => <p className={message.startsWith('You:') ? 'chat-user' : 'muted'} key={`${message}-${index}`}>{message}</p>)}{matches.map(match => <Link className="chat-product" to={`/products/${match.product_id}`} onClick={() => setChatOpen(false)} key={match.product_id}><img src={`${API}/images/${match.image_file_path.split('/').pop()}`} alt={match.name} /><span><b>{match.name}</b><small>${match.price.toFixed(2)} · {match.garment_type}</small></span></Link>)}</div><form className="chat-input" onSubmit={send}><input value={draft} onChange={e => setDraft(e.target.value)} placeholder="Ask a question…" /><button type="submit">➤</button></form></div>}</>
}

function Home() { return <Layout><section className="hero"><div><p className="eyebrow">YOUR CAMPUS. YOUR COLORS.</p><h1>Wear the place<br/><em>you belong.</em></h1><p className="hero-copy">Thoughtful campus apparel for the people, places, and traditions that make your university feel like home.</p><Link className="button" to="/products">Shop the collection <span>→</span></Link></div><div className="hero-art"><div className="sun"></div><div className="art-card">CAMPUS<br/><strong>CUSTOMS</strong><small>YALE UNIVERSITY</small></div></div></section><section className="values"><div><b>01</b><h3>Made for your moment</h3><p>From first day to final walk across the stage, find pieces that carry your story forward.</p></div><div><b>02</b><h3>Built around belonging</h3><p>Explore designs inspired by schools, teams, clubs, and the communities you choose.</p></div><div><b>03</b><h3>Easy to make yours</h3><p>Browse clear details, sizes, colors, and live stock before you choose your next favorite.</p></div></section></Layout> }

function Products() { const [products, setProducts] = useState<Product[]>([]); const [q, setQ] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { fetch(`${API}/api/products`).then(r => { if (!r.ok) throw new Error('Products could not be loaded.') ; return r.json() }).then(setProducts).catch(err => setError(err instanceof Error ? err.message : 'Products could not be loaded.')).finally(() => setLoading(false)) }, []); const filtered = products.filter(p => `${p.name} ${p.garment_type} ${p.search_tags}`.toLowerCase().includes(q.toLowerCase())); return <Layout><section className="page-head"><p className="eyebrow">THE COLLECTION</p><h1>Find your <em>everyday favorite.</em></h1><p>Campus staples, school spirit, and pieces made to move with you.</p><input className="search" value={q} onChange={e => setQ(e.target.value)} placeholder="Search products, teams, schools…" aria-label="Search products" /></section>{loading && <p className="loading">Loading products…</p>}{error && <p className="empty form-error">{error} Please check that the shop server is running.</p>}{!loading && !error && <><section className="grid">{filtered.map(p => <ProductCard key={p.product_id} product={p} />)}</section>{!filtered.length && <p className="empty">No products found. Try a different search.</p>}</>}</Layout> }
function ProductCard({ product }: { product: Product }) { return <Link className="product-card" to={`/products/${product.product_id}`}><div className="product-image"><img src={imageUrl(product)} alt={product.name} /></div><div className="product-meta"><div><h3>{product.name}</h3><p>{product.garment_type}</p><p>{product.description}</p></div><strong>${product.price.toFixed(2)}</strong></div></Link> }
function ProductPage() { const { id } = useParams(); const [product, setProduct] = useState<Product | null>(null); const [stock, setStock] = useState<Stock[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { fetch(`${API}/api/products/${id}`).then(r => { if (!r.ok) throw new Error('Product not found.') ; return r.json() }).then(d => { setProduct(d.product); setStock(d.inventory) }).catch(err => setError(err instanceof Error ? err.message : 'Product could not be loaded.')).finally(() => setLoading(false)) }, [id]); if (loading) return <Layout><p className="loading">Loading product details…</p></Layout>; if (error || !product) return <Layout><section className="empty"><h2>We couldn’t find that product.</h2><p>{error || 'The product may no longer be available.'}</p><Link className="back" to="/products">← Back to products</Link></section></Layout>; return <Layout><section className="detail"><div className="detail-image"><img src={imageUrl(product)} alt={product.name} /></div><div className="detail-copy"><p className="eyebrow">{product.garment_type}</p><h1>{product.name}</h1><div className="price">${product.price.toFixed(2)}</div><p className="description">{product.description}</p><p className="label">Available sizes & stock</p><div className="sizes">{stock.map(s => <span className={s.quantity === 0 ? 'sold' : ''} key={s.size}>{s.size} <b>{s.quantity > 0 ? `${s.quantity} left` : 'Sold out'}</b></span>)}</div><button className="button">Add to bag <span>→</span></button><Link className="back" to="/products">← Back to products</Link></div></section></Layout> }
function About() { return <Layout><section className="about"><p className="eyebrow">OUR STORY</p><h1>More than a logo.<br/><em>A feeling.</em></h1><p className="lead">Campus Customs is a collection of pieces for the moments that stay with you. We celebrate the daily rituals, unexpected friendships, and small traditions that turn a campus into your place.</p><div className="about-grid"><div><span>01 /</span><h2>For the in-between moments</h2><p>Morning classes, late-night walks, and everything that happens between the big events. Our collection is designed for real campus life.</p></div><div><span>02 /</span><h2>Wear what connects you</h2><p>Find your school, your team, your people. We make it simple to carry the communities you care about wherever you go.</p></div></div></section></Layout> }
function FormPage({ account = false }: { account?: boolean }) { const [message, setMessage] = useState(''); const [error, setError] = useState(''); const submit = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setMessage(''); setError(''); const form = new FormData(e.currentTarget); const payload = account ? { first_name: String(form.get('first_name')), last_name: String(form.get('last_name')), email: String(form.get('email')), password: String(form.get('password')) } : { email: String(form.get('email')), password: String(form.get('password')) }; try { const response = await fetch(`${API}/api/auth/${account ? 'register' : 'login'}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || 'Request failed'); localStorage.setItem('campus_customs_user_id', String(data.user.id)); window.dispatchEvent(new Event('campus-customs-auth')); setMessage(account ? 'Account created successfully.' : `Welcome back, ${data.user.first_name}.`); e.currentTarget.reset() } catch (err) { setError(err instanceof Error ? err.message : 'Request failed') } }; return <Layout><section className="form-page"><p className="eyebrow">CAMPUS CUSTOMS</p><h1>{account ? 'Create your account.' : 'Welcome back.'}</h1><p>{account ? 'Save favorites and keep your campus collection close.' : 'Log in to continue your campus story.'}</p><form onSubmit={submit}>{account && <><input name="first_name" placeholder="First name" required /><input name="last_name" placeholder="Last name" required /></>}<input name="email" type="email" placeholder="Email address" required /><input name="password" type="password" minLength={account ? 8 : 1} placeholder="Password" required /><button className="button">{account ? 'Create account' : 'Log in'} <span>→</span></button></form>{message && <p className="form-success">{message}</p>}{error && <p className="form-error">{error}</p>}</section></Layout> }
function App() { return <Routes><Route path="/" element={<Home />} /><Route path="/products" element={<Products />} /><Route path="/products/:id" element={<ProductPage />} /><Route path="/about" element={<About />} /><Route path="/login" element={<FormPage />} /><Route path="/create-account" element={<FormPage account />} /></Routes> }
createRoot(document.getElementById('root')!).render(<BrowserRouter><App /></BrowserRouter>)
